<?php
// Your MySQL database hostname.
define('db_host','localhost');
// Your MySQL database username.
define('db_user','root');
// Your MySQL database password.
define('db_pass','');
// Your MySQL database name.
define('db_name','phpgallery_advanced');
// Your MySQL database charset.
define('db_charset','utf8');
/* Media */
// If enabled, the media popup dialog will appear as opposed to being redirected to a new page.
define('media_popup', true);
// Default grid width for media in pixels.
define('media_grid_default_width', 354);
// Default grid height for media in pixels.
define('media_grid_default_height', 240);
/* Upload */
// If enabled, the image is compressed with a value lower than 100 and therefore the file size is reduced.
define('image_quality', 100);
// If enabled, the media orientation will be corrected when selecting media on responsive devices.
define('correct_image_orientation', false);
// The ImageMagick PHP extension is required to convert SVG images to PNG images.
define('convert_svg_to_png', true);
// The max width for uploaded images (-1 = no max width).
define('image_max_width', -1);
// The max height for uploaded images (-1 = no max height).
define('image_max_height', -1);
// If enabled, thumbnails are autogenerated for images.
define('auto_generate_image_thumbnail', true);
// The max width for autogenerated thumbnails.
define('auto_generate_image_thumbnail_max_width', 354);
// The max height for autogenerated thumbnails.
define('auto_generate_image_thumbnail_max_height', 354);
// Image max filesize, measured in bytes (5MB default).
define('image_max_size', 5000000);
// Audio max filesize, measured in bytes (20MB default).
define('audio_max_size', 20000000);
// Video max filesize, measured in bytes (100MB default).
define('video_max_size', 100000000);
// If enabled, uploaded media will be required for approval by an administrator.
define('approval_required', true);
// If enabled, the user must be authenticated to upload media files.
define('authentication_required', true);
// PHP global settings; you can either adjust the values below or edit them in the php.ini file
// Increase the max upload file size
ini_set('post_max_size', '200M');
ini_set('upload_max_filesize', '200M');
?>